default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  min_messages: warning
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: open-rtb-development

test:
  <<: *default
  database: open-rtb-test

production:
  <<: *default
  database: db/production.sqlite3
